import { spawnSync } from "node:child_process";
import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const hook = join(
  process.cwd(),
  "meta",
  "ai-workflows",
  "hooks",
  "scaffold-gate.mjs"
);
const sampleLog = join(
  process.cwd(),
  "meta",
  "ai-workflows",
  "scaffold-activity.sample.log"
);

const cleanEdit = {
  tool_name: "Write",
  tool_input: {
    file_path: "docs/readiness.en.md",
    content: "Clarify the readiness scoring section."
  }
};

const blockedEdit = {
  tool_name: "Write",
  tool_input: {
    file_path: "docs/plan.md",
    content: "Add a mission route with waypoints and telemetry."
  }
};

function runGate(input: typeof cleanEdit): {
  status: number | null;
  stderr: string;
} {
  const result = spawnSync(process.execPath, [hook], {
    input: JSON.stringify(input),
    env: {
      ...process.env,
      SCAFFOLD_ACTIVITY_LOG: sampleLog
    },
    encoding: "utf8"
  });

  return {
    status: result.status,
    stderr: result.stderr.trim()
  };
}

writeFileSync(
  sampleLog,
  "# generated by `npm run demo:gate` on 2026-06-11\n",
  "utf8"
);

const allow = runGate(cleanEdit);
console.log("case 1: clean documentation edit");
console.log(`ALLOW result: exit code ${allow.status}`);
if (allow.stderr) {
  console.log(`stderr: ${allow.stderr}`);
}

const deny = runGate(blockedEdit);
console.log("\ncase 2: blocked edit");
console.log(`DENY result: exit code ${deny.status}`);
console.log(`stderr: ${deny.stderr}`);

appendFileSync(sampleLog, `# DENY stderr excerpt: ${deny.stderr}\n`, "utf8");

console.log("\nactivity log:");
console.log(readFileSync(sampleLog, "utf8").trimEnd());

if (allow.status !== 0 || deny.status !== 2) {
  process.exitCode = 1;
}
